# Generated by Django 4.2.4 on 2023-08-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_hr_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
