# Generated by Django 4.2.4 on 2023-08-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_delete_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HR',
        ),
    ]
