# Generated by Django 4.2.4 on 2023-08-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_delete_hr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
