# Generated by Django 4.2.4 on 2023-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('leave_id', models.AutoField(primary_key=True, serialize=False)),
                ('leave_typename', models.CharField(max_length=100)),
            ],
        ),
    ]
