# Generated by Django 4.2.4 on 2023-08-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0008_emp_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_days', models.IntegerField(max_length=10)),
                ('status', models.IntegerField(max_length=20)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.emp_master')),
                ('leave_typename', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrms.leavetype')),
            ],
        ),
    ]
