# Generated by Django 4.2.4 on 2023-08-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0009_emp_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leaves',
            name='no_of_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='emp_leaves',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
