# Generated by Django 4.2.4 on 2023-08-10 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_alter_emp_leaves_no_of_days_alter_emp_leaves_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(max_length=10)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.emp_master')),
                ('leave_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.leavetype')),
            ],
        ),
    ]
