# Generated by Django 4.2.4 on 2023-08-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_leave_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='leave_typename',
            field=models.CharField(max_length=100),
        ),
    ]
