# Generated by Django 4.2.4 on 2023-08-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_alter_leave_application_leave_typename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp_leaves',
        ),
    ]
