# Generated by Django 4.2.4 on 2023-08-16 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0016_emp_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leaves',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emp_leaves',
            name='leave_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emp_leaves',
            name='no_of_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
