# Generated by Django 4.2.4 on 2023-08-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_alter_emp_leaves_emp_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leaves',
            name='leave_typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrms.leavetype'),
        ),
    ]
