# Generated by Django 4.2.4 on 2023-08-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_emp_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leaves',
            name='leave_typename',
            field=models.CharField(max_length=50),
        ),
    ]
