# Generated by Django 4.2.4 on 2023-08-16 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_alter_emp_leaves_leave_typename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp_leaves',
        ),
    ]
