# Generated by Django 4.2.4 on 2023-08-17 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_emp_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_application',
            name='leave_typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hrms.leavetype'),
        ),
    ]
