# Generated by Django 4.2.4 on 2023-08-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0024_alter_leave_application_leave_typename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leaves',
            name='status',
            field=models.CharField(default='3', max_length=50),
        ),
    ]
