# Generated by Django 4.2.3 on 2023-08-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0025_alter_emp_leaves_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='entitlement',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='taken',
            field=models.IntegerField(default=0),
        ),
    ]
