# Generated by Django 4.2.3 on 2023-08-18 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0026_customuser_entitlement_customuser_taken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
