# Generated by Django 4.2.3 on 2023-08-22 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0028_remove_leave_entitlement_emp_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Entitlement',
            fields=[
                ('ent_id', models.AutoField(primary_key=True, serialize=False)),
                ('no_of_days', models.IntegerField()),
                ('leave_typename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.leavetype')),
            ],
        ),
    ]
