# Generated by Django 4.2.3 on 2023-08-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0030_emp_leave_entitlement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp_Leave_Entitlement',
        ),
    ]
