# Generated by Django 4.2.3 on 2023-08-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0031_delete_emp_leave_entitlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_entitlement',
            name='leave_period',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
