# Generated by Django 4.2.3 on 2023-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0032_leave_entitlement_leave_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='entitlement',
        ),
        migrations.AddField(
            model_name='customuser',
            name='entitlement',
            field=models.ManyToManyField(to='hrms.leave_entitlement'),
        ),
    ]
