# Generated by Django 4.2.3 on 2023-08-23 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0034_emp_leaves_application_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leaves',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
