# Generated by Django 4.2.3 on 2023-08-24 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0035_alter_emp_leaves_emp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.IntegerField(default=0)),
                ('leave_typename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
