# Generated by Django 4.2.3 on 2023-08-24 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0036_leavetaken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveTaken',
        ),
    ]
