# Generated by Django 4.2.3 on 2023-08-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0038_customuser_leave_balance_type1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='leave_balance_type1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='leave_balance_type2',
        ),
        migrations.DeleteModel(
            name='LeaveTaken',
        ),
    ]
