# Generated by Django 4.2.3 on 2023-08-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0040_customuser_leave_balance1_customuser_leave_balance2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp_leaves',
            name='leave_balance',
        ),
    ]
