# Generated by Django 4.2.3 on 2023-09-04 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0042_remove_customuser_entitlement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('pancard', models.FileField(upload_to='pancards/')),
                ('aadharcard', models.FileField(upload_to='aadharcards/')),
            ],
        ),
    ]
