# Generated by Django 4.2.3 on 2023-09-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0043_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
