# Generated by Django 4.2.3 on 2023-09-05 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0045_employee_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee_documents',
        ),
    ]
