# Generated by Django 4.2.3 on 2023-09-05 11:28

from django.db import migrations, models
import hrms.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0047_employee_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_documents',
            name='aadharcard',
            field=models.FileField(upload_to=hrms.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='employee_documents',
            name='appointment_letter',
            field=models.FileField(upload_to=hrms.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='employee_documents',
            name='educational_certificates',
            field=models.FileField(upload_to=hrms.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='employee_documents',
            name='pancard',
            field=models.FileField(upload_to=hrms.models.generate_filename),
        ),
        migrations.AlterField(
            model_name='employee_documents',
            name='passport_size_photo',
            field=models.FileField(upload_to=hrms.models.generate_filename),
        ),
    ]
