# Generated by Django 4.2.3 on 2023-09-09 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0048_alter_employee_documents_aadharcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_leaves',
            name='mg_conformation',
            field=models.CharField(default='3', max_length=50),
        ),
    ]
