# Generated by Django 4.2.3 on 2023-09-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0052_remove_customuser_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
