# Generated by Django 4.2.3 on 2023-09-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0053_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
    ]
