# Generated by Django 4.2.3 on 2023-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0054_remove_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
