# Generated by Django 4.2.3 on 2023-09-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0056_customuser_biits_id_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='biits_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
