# Generated by Django 4.2.3 on 2023-09-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0061_rename_onboarding_date_customuser_joining_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pancard_number',
        ),
    ]
