# Generated by Django 4.2.3 on 2023-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0065_alter_emp_leaves_mg_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_leaves',
            name='hr_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
