# Generated by Django 4.2.3 on 2023-09-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0066_emp_leaves_hr_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_leaves',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
