# Generated by Django 4.2.3 on 2023-09-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0067_emp_leaves_approved_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Onboardingform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aadhar_number', models.CharField(max_length=50, unique=True)),
                ('pan_number', models.CharField(max_length=50, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('permenent_address', models.CharField(max_length=200)),
                ('emergency_contact', models.IntegerField()),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('spouse_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('educational_documents', models.FileField(upload_to='')),
                ('name_of_the_bank', models.CharField(max_length=50)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('year_of_experience', models.CharField(max_length=30)),
                ('reason_for_resignation', models.CharField(blank=True, max_length=200, null=True)),
                ('uan_number', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
