# Generated by Django 4.2.3 on 2023-09-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0068_emp_onboardingform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_onboardingform',
            name='emergency_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='emp_onboardingform',
            name='phone',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
