# Generated by Django 4.2.3 on 2023-09-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0069_alter_emp_onboardingform_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_onboardingform',
            name='hr_verification',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
