# Generated by Django 4.2.3 on 2023-09-20 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0070_emp_onboardingform_hr_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_onboardingform',
            old_name='name',
            new_name='username',
        ),
    ]
