# Generated by Django 4.2.3 on 2023-09-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0073_remove_emp_onboardingform_educational_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='form_id',
            field=models.IntegerField(default=0),
        ),
    ]
